import type { TripPlan } from "../types/trip";

/** A minimal but complete TripPlan for rendering tests. */
export const SAMPLE_PLAN: TripPlan = {
  trip_id: "test-uuid",
  input: {
    current_location: "Chicago, IL",
    pickup_location: "Indianapolis, IN",
    dropoff_location: "Nashville, TN",
    current_cycle_used_hours: 5,
    trip_start: "2026-07-20T08:00:00-05:00",
  },
  summary: {
    total_distance_miles: 450,
    raw_driving_minutes: 450,
    compliant_trip_minutes: 570,
    departure_at: "2026-07-20T08:00:00-05:00",
    arrival_at: "2026-07-20T17:30:00-05:00",
    number_of_log_days: 1,
    fuel_stop_count: 0,
    rest_break_count: 0,
    overnight_rest_count: 0,
    cycle_restart_count: 0,
  },
  route: {
    geometry: {
      type: "LineString",
      coordinates: [
        [-87.63, 41.88],
        [-86.16, 39.77],
        [-86.78, 36.16],
      ],
    },
    waypoints: [
      { type: "current", label: "Chicago, IL", coordinate: [-87.63, 41.88] },
      { type: "pickup", label: "Indianapolis, IN", coordinate: [-86.16, 39.77] },
      { type: "dropoff", label: "Nashville, TN", coordinate: [-86.78, 36.16] },
    ],
    instructions: [
      { text: "Head south on I-65", name: "I-65 S", distance_miles: 180, duration_minutes: 180 },
      { text: "Continue on I-65", name: "I-65 S", distance_miles: 270, duration_minutes: 270 },
    ],
  },
  timeline: [
    {
      type: "driving",
      duty_status: "DRIVING",
      start_at: "2026-07-20T08:00:00-05:00",
      end_at: "2026-07-20T11:00:00-05:00",
      duration_minutes: 180,
      distance_miles: 180,
      coordinate: [-87.63, 41.88],
      location_label: "Chicago, IL",
      description: "Driving",
      reason_code: "",
    },
    {
      type: "pickup",
      duty_status: "ON_DUTY_NOT_DRIVING",
      start_at: "2026-07-20T11:00:00-05:00",
      end_at: "2026-07-20T12:00:00-05:00",
      duration_minutes: 60,
      distance_miles: 0,
      coordinate: [-86.16, 39.77],
      location_label: "Indianapolis, IN",
      description: "Pickup",
      reason_code: "PICKUP",
    },
    {
      type: "dropoff",
      duty_status: "ON_DUTY_NOT_DRIVING",
      start_at: "2026-07-20T16:30:00-05:00",
      end_at: "2026-07-20T17:30:00-05:00",
      duration_minutes: 60,
      distance_miles: 0,
      coordinate: [-86.78, 36.16],
      location_label: "Nashville, TN",
      description: "Drop-off",
      reason_code: "DROPOFF",
    },
  ],
  daily_logs: [
    {
      date: "2026-07-20",
      from_label: "Chicago, IL",
      to_label: "Nashville, TN",
      total_miles: 450,
      segments: [
        { duty_status: "OFF_DUTY", start_minute: 0, end_minute: 480, event_type: null, is_event_start: false, label: "" },
        { duty_status: "DRIVING", start_minute: 480, end_minute: 660, event_type: "driving", is_event_start: true, label: "Chicago, IL" },
        { duty_status: "ON_DUTY_NOT_DRIVING", start_minute: 660, end_minute: 720, event_type: "pickup", is_event_start: true, label: "Indianapolis, IN" },
        { duty_status: "DRIVING", start_minute: 720, end_minute: 990, event_type: "driving", is_event_start: true, label: "Indianapolis, IN" },
        { duty_status: "ON_DUTY_NOT_DRIVING", start_minute: 990, end_minute: 1050, event_type: "dropoff", is_event_start: true, label: "Nashville, TN" },
        { duty_status: "OFF_DUTY", start_minute: 1050, end_minute: 1440, event_type: null, is_event_start: false, label: "" },
      ],
      totals: { OFF_DUTY: 870, SLEEPER_BERTH: 0, DRIVING: 450, ON_DUTY_NOT_DRIVING: 120 },
      remarks: [
        { time: "08:00", location: "Chicago, IL", activity: "Began driving" },
        { time: "11:00", location: "Indianapolis, IN", activity: "Pickup" },
      ],
      recap: { on_duty_minutes_today: 570, cycle_used_minutes_end_of_day: 870, cycle_hours_available: 55.5 },
      metadata: {
        driver_name: "Assessment Driver",
        carrier: "Spotter Assessment Carrier",
        main_office: "Chicago, IL",
        vehicle: "TRACTOR-001 / TRAILER-001",
        shipping_document: "ASSESSMENT-LOAD",
        is_demo: true,
      },
    },
  ],
  assumptions: ["Property-carrying commercial motor vehicle driver in interstate commerce."],
  warnings: ["This is an assessment/demo trip planner, not a certified ELD."],
};
